image: milthorpe/comp1110-2021-s1-gitlab-ci:0.1.2

stages:
  - integrity
  - compliance
  - build
  - test

before_script:
  - export PATH_TO_FX=/usr/share/openjfx/lib
  - export JAVAFX_OPTIONS="--module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml,javafx.media"
  - export CP=src:/ass2/comp1110-ass2-tests.jar:/shared/junit-platform-console-standalone-1.7.0.jar
  - export JUNIT="java $JAVAFX_OPTIONS -jar /shared/junit-platform-console-standalone-1.7.0.jar --class-path $CP --disable-banner"

integrity:
  tags:
    - comp1110
  stage: integrity
  script:
    - python3 /validate.py --integrity comp1110-ass2

compliance:
  tags:
    - comp1110
  stage: compliance
  script:
    - python3 /validate.py --gitlablogin ${GITLAB_USER_LOGIN} --gitlabuser "${GITLAB_USER_NAME}" --gitlabprojectname "${CI_PROJECT_NAME}" --assignment /compliance-ass2.yml


build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding utf-8 $JAVAFX_OPTIONS -cp $CP $(find src -name "*.java")
  artifacts:
    paths:
      - src/comp1110/ass2/*.class
      - src/comp1110/ass2/*/*.class

task2:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.IsSharedStateWellFormedTest
  allow_failure: true

task3:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.IsPlayerStateWellFormedTest
  allow_failure: true

task5:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.DrawTileFromBagTest
  allow_failure: true

task6:
    tags:
      - comp1110
    stage: test
    script:
      - $JUNIT -c=comp1110.ass2.RefillFactoriesTest
    allow_failure: true

task7:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.GetBonusPointsTest
  allow_failure: true

task8:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.NextRoundTest
  allow_failure: true

task9:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.IsStateValidTest
  allow_failure: true

task10:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.IsMoveValidTest
  allow_failure: true

task11:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.ApplyMoveTest
  allow_failure: true

task13:
  tags:
    - comp1110
  stage: test
  script:
    - $JUNIT -c=comp1110.ass2.GenerateActionTest
  allow_failure: true

## Local Variables:
## mode: yaml
## End:
